### ISSUE TITLE
Hola!!

### ISSUE THREAD

**Issue by murpholinox** [pablomario/Manjaro-simple-conky-theme#1]
Me encanta el conky pero me sale la fecha en inglés. Sabes cómo arreglarlo para que salga en español?

**Comment by murpholinox** [comment]
Ya se arregló! Tenía que poner `template9="es_MX.UTF-8"` y luego esto lo dejé mejor así `date +"%A %d de %B"`

**Comment by pablomario** [comment]
@murpholinox Gracias por los comentarios, voy a revisar el tema de las fechas y actualizo. ;)
